import { PrismaClient, ResourceStatus } from '@prisma/client';

export const seedingProductsData = async (prisma: PrismaClient) => {
    console.log('  - Seeding products...');

    // Lấy tất cả seller users có seller profile (đã được duyệt)
    const sellers = await prisma.sellerProfile.findMany({
        where: { status: ResourceStatus.APPROVED },
        include: { user: true },
        take: 20,
    });

    if (sellers.length === 0) {
        console.warn('    ⚠️ No approved sellers found. Skipping product seeding.');
        return;
    }

    const categories = await prisma.category.findMany();
    const catPhones = categories.find(c => c.slug === 'dien-thoai');
    const catLaptops = categories.find(c => c.slug === 'laptop');
    const catFashion = categories.find(c => c.slug === 'thoi-trang');
    const catAccessories = categories.find(c => c.slug === 'phu-kien');
    const catHome = categories.find(c => c.slug === 'noi-that');
    const catBeauty = categories.find(c => c.slug === 'my-pham');
    const catSports = categories.find(c => c.slug === 'the-thao');

    // 25 sản phẩm mẫu
    const products = [
        {
            name: 'iPhone 15 Pro Max 256GB - VN/A',
            slug: 'iphone-15-pro-max-256gb',
            description:
                'iPhone 15 Pro Max là chiếc iPhone mạnh mẽ nhất từ trước đến nay với khung viền Titanium siêu bền, chip A17 Pro đột phá.',
            price: 30990000,
            originalPrice: 34990000,
            discount: 11,
            stock: 50,
            sku: 'IP15PM-256',
            images: [
                'https://images.unsplash.com/photo-1696446701796-da61225697cc?q=80&w=800',
                'https://images.unsplash.com/photo-1695048133142-1a20484d25fa?q=80&w=800',
            ],
            weight: 221,
            categoryId: catPhones?.id,
            sellerId: sellers[0].userId,
            status: ResourceStatus.APPROVED,
            viewCount: 1540,
            soldCount: 85,
            ratingAvg: 4.9,
            ratingCount: 42,
            isFeatured: true,
            specifications: {
                screen: '6.7 inch, Super Retina XDR OLED',
                cpu: 'Apple A17 Pro (3 nm)',
                ram: '8 GB',
                camera: 'Chính 48 MP',
                battery: '4441 mAh',
            },
            attributes: { brand: 'Apple', color: 'Titan Tự Nhiên', storage: '256GB' },
        },
        {
            name: 'Samsung Galaxy S24 Ultra 12GB/256GB',
            slug: 'samsung-galaxy-s24-ultra',
            description:
                'Galaxy AI is here. Trải nghiệm quyền năng của trí tuệ nhân tạo trên Samsung Galaxy S24 Ultra.',
            price: 26490000,
            originalPrice: 33990000,
            discount: 22,
            stock: 30,
            sku: 'S24U-256',
            images: ['https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?q=80&w=800'],
            weight: 232,
            categoryId: catPhones?.id,
            sellerId: sellers[1].userId,
            status: ResourceStatus.APPROVED,
            viewCount: 850,
            soldCount: 12,
            isFeatured: true,
            specifications: {
                screen: '6.8 inch, Dynamic LTPO AMOLED 2X',
                cpu: 'Snapdragon 8 Gen 3',
                ram: '12 GB',
                camera: '200 MP',
                battery: '5000 mAh',
            },
        },
        {
            name: 'Laptop Gaming ASUS ROG Zephyrus G14',
            slug: 'asus-rog-zephyrus-g14',
            description:
                'ROG Zephyrus G14 là chiếc laptop gaming 14 inch mạnh mẽ nhất thế giới với chip Ryzen 9 và GPU RTX 40-series.',
            price: 45990000,
            originalPrice: 49990000,
            discount: 8,
            stock: 15,
            sku: 'G14-2024',
            images: ['https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?q=80&w=800'],
            weight: 1500,
            categoryId: catLaptops?.id,
            sellerId: sellers[2].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 25,
            viewCount: 2100,
            ratingAvg: 4.8,
            ratingCount: 12,
            specifications: {
                cpu: 'AMD Ryzen 9 8945HS',
                gpu: 'NVIDIA GeForce RTX 4060',
                ram: '16GB LPDDR5X',
                ssd: '1TB M.2 NVMe',
            },
        },
        {
            name: 'Áo thun Polo Nam Uniqlo Supima Cotton',
            slug: 'ao-polo-nam-uniqlo-supima',
            description: 'Áo Polo với chất liệu Supima Cotton cao cấp, mềm mại và thoáng mát.',
            price: 499000,
            originalPrice: 599000,
            discount: 16,
            stock: 100,
            sku: 'UQ-POLO-S',
            images: ['https://images.unsplash.com/photo-1521572267360-ee0c2909d518?q=80&w=800'],
            categoryId: catFashion?.id,
            sellerId: sellers[3].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 450,
            ratingAvg: 4.5,
            ratingCount: 120,
            attributes: { material: 'Cotton', style: 'Polo' },
        },
        {
            name: 'Sony WH-1000XM5 Noise Cancelling Headphones',
            slug: 'sony-wh-1000xm5',
            description: 'Tai nghe chống ồn hàng đầu thế giới với chất âm đỉnh cao.',
            price: 7490000,
            originalPrice: 8490000,
            discount: 12,
            stock: 20,
            sku: 'SONY-XM5',
            images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?q=80&w=800'],
            sellerId: sellers[4].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 68,
            viewCount: 3200,
            ratingAvg: 4.7,
            ratingCount: 56,
            isNew: true,
        },
        // Thêm 20 sản phẩm mới
        {
            name: 'MacBook Pro 14 inch M3 Pro',
            slug: 'macbook-pro-14-m3-pro',
            description: 'MacBook Pro với chip M3 Pro, hiệu năng vượt trội cho dev và designer.',
            price: 47990000,
            originalPrice: 52990000,
            discount: 9,
            stock: 25,
            sku: 'MBP14-M3',
            images: ['https://images.unsplash.com/photo-1517336714731-489689fd1ca8?q=80&w=800'],
            categoryId: catLaptops?.id,
            sellerId: sellers[0].userId,
            status: ResourceStatus.APPROVED,
            viewCount: 1200,
            soldCount: 45,
            ratingAvg: 4.9,
            ratingCount: 28,
            isFeatured: true,
        },
        {
            name: 'Tai nghe AirPods Pro 2nd Gen',
            slug: 'airpods-pro-2',
            description: 'Tai nghe True Wireless với chống ồn chủ động và Transparency mode.',
            price: 5490000,
            originalPrice: 5990000,
            discount: 8,
            stock: 80,
            sku: 'AIRPODS-PRO2',
            images: ['https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?q=80&w=800'],
            categoryId: catAccessories?.id,
            sellerId: sellers[1].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 230,
            ratingAvg: 4.8,
            ratingCount: 156,
        },
        {
            name: 'Đồng hồ Apple Watch Series 9 GPS 45mm',
            slug: 'apple-watch-series-9',
            description: 'Đồng hồ thông minh với màn hình Retina Always-On, đo nhịp tim, ECG.',
            price: 8990000,
            originalPrice: 9990000,
            discount: 10,
            stock: 40,
            sku: 'AWS9-45',
            images: ['https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?q=80&w=800'],
            categoryId: catAccessories?.id,
            sellerId: sellers[2].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 89,
            ratingAvg: 4.7,
            ratingCount: 67,
        },
        {
            name: 'Bàn phím cơ Keychron K8 Pro',
            slug: 'keychron-k8-pro',
            description: 'Bàn phím cơ không dây RGB, hotswap, compatible với Mac và Windows.',
            price: 2590000,
            originalPrice: 2990000,
            discount: 13,
            stock: 60,
            sku: 'KC-K8-PRO',
            images: ['https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=800'],
            categoryId: catAccessories?.id,
            sellerId: sellers[3].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 156,
            ratingAvg: 4.6,
            ratingCount: 89,
        },
        {
            name: 'Chuột không dây Logitech MX Master 3S',
            slug: 'logitech-mx-master-3s',
            description:
                'Chuột ergonomics cao cấp với cảm biến 8000 DPI, hỗ trợ Flow cross-device.',
            price: 2290000,
            originalPrice: 2690000,
            discount: 15,
            stock: 45,
            sku: 'LOGI-MX3S',
            images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?q=80&w=800'],
            categoryId: catAccessories?.id,
            sellerId: sellers[4].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 203,
            ratingAvg: 4.8,
            ratingCount: 134,
        },
        {
            name: 'Xiaomi Redmi Note 13 Pro 5G',
            slug: 'xiaomi-redmi-note-13-pro',
            description: 'Điện thoại tầm trung với camera 200MP, màn hình AMOLED 120Hz.',
            price: 8990000,
            originalPrice: 10990000,
            discount: 18,
            stock: 55,
            sku: 'RN13P-5G',
            images: ['https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?q=80&w=800'],
            categoryId: catPhones?.id,
            sellerId: sellers[5].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 78,
            ratingAvg: 4.5,
            ratingCount: 45,
        },
        {
            name: 'OPPO Find X7 Pro',
            slug: 'oppo-find-x7-pro',
            description: 'Flagship OPPO với camera Hasselblad, chip MediaTek Dimensity 9300.',
            price: 22990000,
            originalPrice: 26990000,
            discount: 15,
            stock: 20,
            sku: 'OPPO-FX7P',
            images: ['https://images.unsplash.com/photo-1598327105666-5b89351aff97?q=80&w=800'],
            categoryId: catPhones?.id,
            sellerId: sellers[6].userId,
            status: ResourceStatus.PENDING,
            viewCount: 650,
            soldCount: 5,
        },
        {
            name: 'Kính râm Ray-Ban Classic Wayfarer',
            slug: 'ray-ban-wayfarer',
            description: 'Kính râm huyền thoại với trục kính chống tia UV400.',
            price: 3590000,
            originalPrice: 4290000,
            discount: 16,
            stock: 35,
            sku: 'RB-WAYFARER',
            images: ['https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=800'],
            categoryId: catAccessories?.id,
            sellerId: sellers[7].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 42,
            ratingAvg: 4.7,
            ratingCount: 28,
        },
        {
            name: 'Túi xách nữ da PU cao cấp',
            slug: 'tui-xach-nu-da-pu',
            description: 'Túi xách thời trang, da PU cao cấp, nhiều ngăn tiện lợi.',
            price: 890000,
            originalPrice: 1290000,
            discount: 31,
            stock: 120,
            sku: 'TX-NU-PU',
            images: ['https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=800'],
            categoryId: catFashion?.id,
            sellerId: sellers[8].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 312,
            ratingAvg: 4.4,
            ratingCount: 89,
        },
        {
            name: 'Máy tính bảng iPad Air M2 11 inch',
            slug: 'ipad-air-m2-11',
            description: 'iPad Air với chip M2, màn hình Liquid Retina, hỗ trợ Apple Pencil.',
            price: 15990000,
            originalPrice: 17990000,
            discount: 11,
            stock: 30,
            sku: 'IPAIR-M2-11',
            images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?q=80&w=800'],
            categoryId: catLaptops?.id,
            sellerId: sellers[9].userId,
            status: ResourceStatus.APPROVED,
            viewCount: 980,
            soldCount: 56,
            ratingAvg: 4.8,
            ratingCount: 34,
        },
        {
            name: 'Loa Bluetooth JBL Flip 6',
            slug: 'jbl-flip-6',
            description: 'Loa bluetooth chống nước IP67, âm bass mạnh, pin 12 giờ.',
            price: 2990000,
            originalPrice: 3490000,
            discount: 14,
            stock: 70,
            sku: 'JBL-FLIP6',
            images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?q=80&w=800'],
            categoryId: catAccessories?.id,
            sellerId: sellers[10].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 189,
            ratingAvg: 4.7,
            ratingCount: 112,
        },
        {
            name: 'Giày sneaker Nike Air Max 90',
            slug: 'nike-air-max-90',
            description: 'Giày sneaker cổ điển với công nghệ Air cushioning êm ái.',
            price: 4590000,
            originalPrice: 5490000,
            discount: 16,
            stock: 25,
            sku: 'NIKE-AM90',
            images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?q=80&w=800'],
            categoryId: catFashion?.id,
            sellerId: sellers[11].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 67,
            ratingAvg: 4.6,
            ratingCount: 45,
        },
        {
            name: 'Bộ dụng cụ pha cà phê espresso',
            slug: 'ca-phe-espresso-kit',
            description: 'Bộ kit pha cà phê espresso cho người yêu cà phê.',
            price: 1890000,
            originalPrice: 2490000,
            discount: 24,
            stock: 40,
            sku: 'ESP-KIT',
            images: ['https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?q=80&w=800'],
            categoryId: catHome?.id,
            sellerId: sellers[12].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 34,
            ratingAvg: 4.5,
            ratingCount: 21,
        },
        {
            name: 'Son môi YSL Rouge Pur Couture',
            slug: 'ysl-rouge-pur-couture',
            description: 'Son môi cao cấp YSL với màu sắc bền lâu, dưỡng ẩm.',
            price: 1150000,
            originalPrice: 1350000,
            discount: 15,
            stock: 50,
            sku: 'YSL-SON',
            images: ['https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=800'],
            categoryId: catBeauty?.id,
            sellerId: sellers[13].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 89,
            ratingAvg: 4.8,
            ratingCount: 56,
        },
        {
            name: 'Bình nước保温 Stanley Adventure',
            slug: 'stanley-adventure',
            description: 'Bình nước giữ nóng/lạnh 24h, chất liệu thép không gỉ 18/8.',
            price: 1350000,
            originalPrice: 1650000,
            discount: 18,
            stock: 65,
            sku: 'STAN-ADV',
            images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=800'],
            categoryId: catSports?.id,
            sellerId: sellers[14].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 145,
            ratingAvg: 4.7,
            ratingCount: 78,
        },
        {
            name: 'Máy ảnh Canon EOS R50 Body',
            slug: 'canon-eos-r50',
            description: 'Máy ảnh mirrorless APS-C mới nhất của Canon, lý tưởng cho beginner.',
            price: 14490000,
            originalPrice: 16990000,
            discount: 15,
            stock: 15,
            sku: 'CANON-R50',
            images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?q=80&w=800'],
            categoryId: catAccessories?.id,
            sellerId: sellers[15].userId,
            status: ResourceStatus.APPROVED,
            viewCount: 780,
            soldCount: 23,
            ratingAvg: 4.6,
            ratingCount: 15,
        },
        {
            name: 'Bàn gaming có đệm ngồi',
            slug: 'ban-gaming-pro',
            description: 'Bàn gaming rộng rãi với đệm ngồi êm ái, RGB lights.',
            price: 3990000,
            originalPrice: 4990000,
            discount: 20,
            stock: 20,
            sku: 'BG-PRO',
            images: ['https://images.unsplash.com/photo-1593640408182-31c70c8268f5?q=80&w=800'],
            categoryId: catHome?.id,
            sellerId: sellers[16].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 18,
            ratingAvg: 4.5,
            ratingCount: 12,
        },
        {
            name: 'Váy midi nữ cao cấp',
            slug: 'vay-midi-nu',
            description: 'Váy midi thanh lịch, chất liệu linen mềm mại, nhiều màu.',
            price: 790000,
            originalPrice: 990000,
            discount: 20,
            stock: 85,
            sku: 'VAY-MIDI',
            images: ['https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?q=80&w=800'],
            categoryId: catFashion?.id,
            sellerId: sellers[17].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 234,
            ratingAvg: 4.6,
            ratingCount: 89,
        },
        {
            name: 'Điều hòa Samsung Inverter 12000BTU',
            slug: 'dieu-hoa-samsung-inverter',
            description: 'Máy lạnh inverter tiết kiệm điện, làm lạnh nhanh, lọc không khí.',
            price: 8590000,
            originalPrice: 10590000,
            discount: 19,
            stock: 18,
            sku: 'DH-SAM-12',
            images: ['https://images.unsplash.com/photo-1585771724684-38269d6639fd?q=80&w=800'],
            categoryId: catHome?.id,
            sellerId: sellers[18].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 12,
            ratingAvg: 4.4,
            ratingCount: 8,
        },
        {
            name: 'Đèn bàn LED cao cấp Eye Care',
            slug: 'den-ban-led-eye-care',
            description: 'Đèn bàn LED bảo vệ mắt, điều chỉnh độ sáng và nhiệt độ màu.',
            price: 590000,
            originalPrice: 790000,
            discount: 25,
            stock: 95,
            sku: 'DEN-LED-EC',
            images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=800'],
            categoryId: catHome?.id,
            sellerId: sellers[19].userId,
            status: ResourceStatus.APPROVED,
            soldCount: 267,
            ratingAvg: 4.7,
            ratingCount: 134,
        },
    ];

    for (const p of products) {
        const product = await prisma.product.upsert({
            where: { slug: p.slug },
            update: {
                images: p.images,
                price: p.price,
                originalPrice: p.originalPrice,
            },
            create: {
                ...p,
                price: p.price,
                originalPrice: p.originalPrice,
            },
        });

        // Thêm một số variant mẫu nếu là iPhone
        if (p.slug.includes('iphone')) {
            await prisma.productVariant.deleteMany({
                where: { productId: product.id },
            });

            await prisma.productVariant.createMany({
                data: [
                    {
                        productId: product.id,
                        name: 'Titan Tự Nhiên',
                        price: p.price,
                        stock: 20,
                        sku: 'IP15PM-256-NAT',
                    },
                    {
                        productId: product.id,
                        name: 'Titan Xanh',
                        price: p.price,
                        stock: 15,
                        sku: 'IP15PM-256-BLU',
                    },
                    {
                        productId: product.id,
                        name: 'Titan Đen',
                        price: p.price,
                        stock: 15,
                        sku: 'IP15PM-256-BLK',
                    },
                ],
            });
        }
    }
};
