import { PrismaClient, VoucherType } from '@prisma/client';

export const seedingPublicVouchersData = async (prisma: PrismaClient) => {
    console.log('  - Seeding 15 public platform vouchers...');

    const now = new Date();
    const in30Days = new Date(now.getTime() + 30 * 24 * 60 * 60 * 1000);
    const in60Days = new Date(now.getTime() + 60 * 24 * 60 * 60 * 1000);
    const in90Days = new Date(now.getTime() + 90 * 24 * 60 * 60 * 1000);

    const vouchers = [
        {
            code: 'WELCOME50K',
            type: VoucherType.FIXED_AMOUNT,
            value: 50000,
            minOrderValue: 200000,
            maxDiscount: null,
            usageLimit: 1000,
            perUserLimit: 1,
            description: 'Giảm 50K cho đơn hàng đầu tiên từ 200K',
            startDate: now,
            endDate: in30Days,
        },
        {
            code: 'FREESHIP100',
            type: VoucherType.FREE_SHIPPING,
            value: 0,
            minOrderValue: 100000,
            maxDiscount: null,
            usageLimit: 500,
            perUserLimit: 2,
            description: 'Miễn phí vận chuyển cho đơn từ 100K',
            startDate: now,
            endDate: in30Days,
        },
        {
            code: 'SALE10PCT',
            type: VoucherType.PERCENTAGE,
            value: 10,
            minOrderValue: 300000,
            maxDiscount: 100000,
            usageLimit: 2000,
            perUserLimit: 3,
            description: 'Giảm 10% tối đa 100K cho đơn từ 300K',
            startDate: now,
            endDate: in60Days,
        },
        {
            code: 'MEGA15PCT',
            type: VoucherType.PERCENTAGE,
            value: 15,
            minOrderValue: 500000,
            maxDiscount: 150000,
            usageLimit: 500,
            perUserLimit: 1,
            description: 'Giảm 15% tối đa 150K cho đơn từ 500K',
            startDate: now,
            endDate: in30Days,
        },
        {
            code: 'SUMMER100K',
            type: VoucherType.FIXED_AMOUNT,
            value: 100000,
            minOrderValue: 500000,
            maxDiscount: null,
            usageLimit: 300,
            perUserLimit: 1,
            description: 'Khuyến mãi hè - Giảm 100K cho đơn từ 500K',
            startDate: now,
            endDate: in60Days,
        },
        {
            code: 'NEWUSER20K',
            type: VoucherType.FIXED_AMOUNT,
            value: 20000,
            minOrderValue: 0,
            maxDiscount: null,
            usageLimit: 5000,
            perUserLimit: 1,
            description: 'Tặng 20K cho khách hàng mới không yêu cầu đơn tối thiểu',
            startDate: now,
            endDate: in90Days,
        },
        {
            code: 'TECH20PCT',
            type: VoucherType.PERCENTAGE,
            value: 20,
            minOrderValue: 1000000,
            maxDiscount: 300000,
            usageLimit: 200,
            perUserLimit: 1,
            description: 'Giảm 20% tối đa 300K cho đơn công nghệ từ 1 triệu',
            startDate: now,
            endDate: in30Days,
        },
        {
            code: 'DOUBLE11',
            type: VoucherType.PERCENTAGE,
            value: 11,
            minOrderValue: 200000,
            maxDiscount: 200000,
            usageLimit: 1100,
            perUserLimit: 2,
            description: 'Siêu sale 11/11 - Giảm 11% tối đa 200K',
            startDate: now,
            endDate: in60Days,
        },
        {
            code: 'FLASH30K',
            type: VoucherType.FIXED_AMOUNT,
            value: 30000,
            minOrderValue: 150000,
            maxDiscount: null,
            usageLimit: 2000,
            perUserLimit: 3,
            description: 'Giảm ngay 30K cho mọi đơn từ 150K',
            startDate: now,
            endDate: in30Days,
        },
        {
            code: 'LOYAL5PCT',
            type: VoucherType.PERCENTAGE,
            value: 5,
            minOrderValue: 0,
            maxDiscount: 50000,
            usageLimit: null,
            perUserLimit: 5,
            description: 'Ưu đãi khách hàng thân thiết - Giảm 5% tối đa 50K không giới hạn đơn',
            startDate: now,
            endDate: in90Days,
        },
        {
            code: 'WEEKEND20K',
            type: VoucherType.FIXED_AMOUNT,
            value: 20000,
            minOrderValue: 100000,
            maxDiscount: null,
            usageLimit: 800,
            perUserLimit: 2,
            description: 'Weekend treat - 20K off orders from 100K',
            startDate: now,
            endDate: in30Days,
        },
        {
            code: 'BULK25PCT',
            type: VoucherType.PERCENTAGE,
            value: 25,
            minOrderValue: 2000000,
            maxDiscount: 400000,
            usageLimit: 150,
            perUserLimit: 1,
            description: 'Big basket bonus - 25% off up to 400K for orders from 2M',
            startDate: now,
            endDate: in60Days,
        },
        {
            code: 'BEAUTY50K',
            type: VoucherType.FIXED_AMOUNT,
            value: 50000,
            minOrderValue: 250000,
            maxDiscount: null,
            usageLimit: 700,
            perUserLimit: 2,
            description: 'Beauty special - 50K off cosmetics orders from 250K',
            startDate: now,
            endDate: in60Days,
        },
        {
            code: 'MIDNIGHTSHIP',
            type: VoucherType.FREE_SHIPPING,
            value: 0,
            minOrderValue: 0,
            maxDiscount: null,
            usageLimit: 300,
            perUserLimit: 1,
            description: 'Midnight free shipping for any order placed 00:00-06:00',
            startDate: now,
            endDate: in30Days,
        },
        {
            code: 'STUDENT10K',
            type: VoucherType.FIXED_AMOUNT,
            value: 10000,
            minOrderValue: 50000,
            maxDiscount: null,
            usageLimit: 2000,
            perUserLimit: 2,
            description: 'Student offer - 10K off orders from 50K',
            startDate: now,
            endDate: in90Days,
        },
    ];

    for (const v of vouchers) {
        await prisma.voucher.upsert({
            where: { code: v.code },
            update: {},
            create: {
                code: v.code,
                type: v.type,
                value: v.value,
                minOrderValue: v.minOrderValue ?? undefined,
                maxDiscount: v.maxDiscount ?? undefined,
                usageLimit: v.usageLimit ?? undefined,
                perUserLimit: v.perUserLimit,
                isActive: true,
                startDate: v.startDate,
                endDate: v.endDate,
                description: v.description,
                sellerId: null, // Platform vouchers
            },
        });
        console.log(`    ✓ Voucher ${v.code} seeded`);
    }
};
